import { test, expect } from '@playwright/test';
import { _electron as electron } from 'playwright';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper to get launch options
const getLaunchOptions = () => ({
  args: [
    'dist/main/main.js',
    ...(process.env.CI ? ['--no-sandbox', '--disable-setuid-sandbox'] : []),
  ],
});

test.describe('Floating Action Buttons - Empty State', () => {
  test('should display centered FAB container in empty state', async () => {
    const app = await electron.launch(getLaunchOptions());
    const window = await app.firstWindow();

    await window.waitForLoadState('domcontentloaded');
    await window.waitForTimeout(2000);

    const centeredFab = window.locator('[data-testid="fab-centered"]');
    await expect(centeredFab).toBeVisible();

    await app.close();
  });

  test('should have Open File button in empty state', async () => {
    const app = await electron.launch(getLaunchOptions());
    const window = await app.firstWindow();

    await window.waitForLoadState('domcontentloaded');
    await window.waitForTimeout(2000);

    // MUI Fab buttons in centered container
    const openFileButton = window.locator('.fab-container.centered button.MuiFab-root').first();
    await expect(openFileButton).toBeVisible();

    await app.close();
  });

  test('should have Download URL button in empty state', async () => {
    const app = await electron.launch(getLaunchOptions());
    const window = await app.firstWindow();

    await window.waitForLoadState('domcontentloaded');
    await window.waitForTimeout(2000);

    // Second FAB button is download
    const downloadButton = window.locator('.fab-container.centered button.MuiFab-root').nth(1);
    await expect(downloadButton).toBeVisible();

    await app.close();
  });
});

test.describe('Floating Action Buttons - With Video', () => {
  // Skip these tests as they require a real video file
  // The placeholder sample-video.mp4 is only 12 bytes and won't load
  // These tests would work with a proper test video generated by ffmpeg

  test.skip('should show FAB menu when video is loaded', async () => {
    // Requires real video file
  });

  test.skip('should have metadata button when video is loaded', async () => {
    // Requires real video file
  });

  test.skip('should have close video button when video is loaded', async () => {
    // Requires real video file
  });

  test.skip('should close video when close button clicked', async () => {
    // Requires real video file
  });

  test.skip('should toggle metadata overlay when metadata button clicked', async () => {
    // Requires real video file
  });
});
